// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NSwag.CodeGeneration.CodeGenerators.TypeScript.Templates
{
    using NJsonSchema;
    using CodeGenerators.TypeScript;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal partial class Angular2ClientTemplate : Angular2ClientTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"import { AppConfig } from '../config/app.config';


export class HQAPIEntity {

    constructor(data?: any) {
        if (data !== undefined) {
            this.id = data[""Id""] !== undefined ? data[""Id""] : 0;
            this.createdBy = data[""CreatedBy""] !== undefined ? data[""CreatedBy""] : 0;
            this.updatedBy = data[""UpdatedBy""] !== undefined ? data[""UpdatedBy""] : 0;
            this.createdOn = data[""CreatedOn""] ? new Date(data[""CreatedOn""].toString()) : null;
            this.updatedOn = data[""UpdatedOn""] ? new Date(data[""UpdatedOn""].toString()) : null;
        }
    }

    /** The unique identifier of this entity */
    id: number; 
    /** The id of the user who created this entity */
    createdBy: number; 
    /** The id of the last user who modified this entity */
    updatedBy: number; 
    /** The date and time this entity was created, in UTC */
    createdOn: Date; 
    /** The last date and time this entity was updated, in UTC */
    updatedOn: Date;
} 

");
            
            #line 31 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.HasOperations){
            
            #line default
            #line hidden
            
            #line 32 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.GenerateClientInterfaces){
            
            #line default
            #line hidden
            this.Write("export interface I");
            
            #line 33 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Class));
            
            #line default
            #line hidden
            this.Write(" {\r\n");
            
            #line 34 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var operation in Model.Operations){
            
            #line default
            #line hidden
            
            #line 35 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasDocumentation){
            
            #line default
            #line hidden
            this.Write("    /**\r\n");
            
            #line 36 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasSummary){
            
            #line default
            #line hidden
            this.Write("     * ");
            
            #line 36 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 37 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 37 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 38 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(parameter.HasDescription){
            
            #line default
            #line hidden
            this.Write("     * @");
            
            #line 38 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 38 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Description ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 39 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 39 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasResultDescription){
            
            #line default
            #line hidden
            this.Write("     * @return ");
            
            #line 39 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 40 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 40 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.IsDeprecated){
            
            #line default
            #line hidden
            this.Write("     * @deprecated\r\n");
            
            #line 41 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("     */\r\n");
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameLower));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(!parameter.IsLast){
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("): Observable<");
            
            #line 42 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(">;\r\n");
            
            #line 43 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 44 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n@Injectable()\r\nexport class ");
            
            #line 47 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Class));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 47 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.GenerateClientInterfaces){
            
            #line default
            #line hidden
            this.Write("implements I");
            
            #line 47 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Class));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 47 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\r\n    private http: Http = null; \r\n    private authHeader: string = undefined; \r" +
                    "\n    private baseUrl: string = undefined; \r\n    protected jsonParseReviver: ");
            
            #line 51 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.SupportsStrictNullChecks){
            
            #line default
            #line hidden
            this.Write("((key: string, value: any) => any) | undefined");
            
            #line 51 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("(key: string, value: any) => any");
            
            #line 51 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(" = undefined;\r\n\r\n    constructor(@Inject(Http) http: Http, appConfig: AppConfig, " +
                    "@Optional() @Inject(API_BASE_URL) baseUrl?: string) {\r\n        this.http = http;" +
                    " \r\n        this.baseUrl = (baseUrl ? baseUrl : (appConfig ? appConfig.getConfig(" +
                    "\'apiUrl\') :  \"");
            
            #line 55 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseUrl));
            
            #line default
            #line hidden
            this.Write(@""")); 
        console.log(""Using api url:"", this.baseUrl);
    }
	
	/**
	 * Sets the authorization header to OAuth
	 */
    setBearerAuthorization(token: string){
        this.authHeader = ""Bearer "" +  token;
    }
	
	/**
	 * Sets the authorization header to Basic auth
	 */
    setBasicAuthorization(userName: string, password: string){
        this.authHeader = ""Basic "" +  btoa(userName + "":"" + password);
    }

	/**
	 * Returns the current authorization header
	 */
	GetAuthHeader(): string{
		return this.authHeader;
	}

");
            
            #line 80 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.IsExtended){
            
            #line default
            #line hidden
            this.Write("\r\n    protected transformOptions(options: RequestOptionsArgs) {\r\n        return o" +
                    "ptions; \r\n    }\r\n\r\n    protected transformResult(url: string, response: Response" +
                    ", processor: (response: Response) => any) {\r\n        return processor(response);" +
                    "\r\n    }\r\n");
            
            #line 89 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 90 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var operation in Model.Operations){
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 92 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasDocumentation){
            
            #line default
            #line hidden
            this.Write("    /**\r\n");
            
            #line 93 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasSummary){
            
            #line default
            #line hidden
            this.Write("     * ");
            
            #line 93 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.Summary));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 94 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 94 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 95 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(parameter.HasDescription){
            
            #line default
            #line hidden
            this.Write("     * @");
            
            #line 95 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 95 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Description ?? ""));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 96 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 96 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 96 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasResultDescription){
            
            #line default
            #line hidden
            this.Write("     * @return ");
            
            #line 96 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultDescription));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 97 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 97 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.IsDeprecated){
            
            #line default
            #line hidden
            this.Write("     * @deprecated\r\n");
            
            #line 98 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("     */\r\n");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("    ");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameLower));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var parameter in operation.Parameters){
            
            #line default
            #line hidden
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Type));
            
            #line default
            #line hidden
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(!parameter.IsLast){
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write(", fromCache = false");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("): Observable<");
            
            #line 99 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write("> {\r\n        ");
            
            #line 100 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplatePartGenerator.RenderRequestUrlCode(operation, 2)));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n        ");
            
            #line 102 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplatePartGenerator.RenderRequestBodyCode(operation, 2)));
            
            #line default
            #line hidden
            this.Write(@"
		var cacheKey = fromCache ? btoa(url_) : null;
        var cacheEntry = fromCache ? localStorage.getItem(cacheKey) : null;

        if(!fromCache || cacheEntry == null){
			console.log('Getting ' + url_ + ' since ' + (fromCache ? 'not in cache' : 'cache is disabled'));
			return this.http.request(url_, ");
            
            #line 108 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.IsExtended){
            
            #line default
            #line hidden
            this.Write("this.transformOptions(");
            
            #line 108 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("{\r\n\t\t\t\tbody: content_,\r\n\t\t\t\tmethod: \"");
            
            #line 110 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.HttpMethodLower));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\theaders: new Headers({\r\n");
            
            #line 112 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var parameter in operation.HeaderParameters){
            
            #line default
            #line hidden
            this.Write("                \"");
            
            #line 113 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.Name));
            
            #line default
            #line hidden
            this.Write("\": ");
            
            #line 113 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameter.VariableName));
            
            #line default
            #line hidden
            this.Write(", \r\n");
            
            #line 114 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            
            #line 115 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasFormParameters){
            
            #line default
            #line hidden
            this.Write("                \'Content-Type\': undefined,\r\n");
            
            #line 116 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\"Content-Type\": \"application/json; charset=UTF-8\",\r\n");
            
            #line 118 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\"Authorization\": this.GetAuthHeader()\r\n\t\t\t\t})\r\n\t\t\t}");
            
            #line 121 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.IsExtended){
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 121 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write(").map((response) => {\r\n\t\t\t\tif(fromCache) {\r\n\t\t\t\t\ttry {\r\n\t\t\t\t\t\tlocalStorage.setIte" +
                    "m(cacheKey, btoa(response.text()));\r\n\t\t\t\t\t} catch(e) {}\r\n\t\t\t\t}\r\n");
            
            #line 127 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.IsExtended){
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn this.transformResult(url_, response, (response) => this.process");
            
            #line 128 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(response));\r\n");
            
            #line 129 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\treturn this.process");
            
            #line 130 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(response);\r\n");
            
            #line 131 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}).catch((response: any, caught: any) => {\r\n\t\t\t\tif (response instanceof Respon" +
                    "se) {\r\n\t\t\t\t\ttry {\r\n");
            
            #line 135 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(Model.IsExtended){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\treturn Observable.of(this.transformResult(url_, response, (response) => thi" +
                    "s.process");
            
            #line 136 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(response)));\r\n");
            
            #line 137 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}else{
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\treturn Observable.of(this.process");
            
            #line 138 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(response));\r\n");
            
            #line 139 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t} catch (e) {\r\n\t\t\t\t\t\treturn <Observable<");
            
            #line 141 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(">><any>Observable.throw(e);\r\n\t\t\t\t\t}\r\n\t\t\t\t} else\r\n\t\t\t\t\treturn <Observable<");
            
            #line 144 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(">><any>Observable.throw(response);\r\n\t\t\t});\r\n\t\t} else {\r\n\t\t\tconsole.log(\'Getting \'" +
                    " + url_ + \' from cache\');\r\n\t\t\treturn new Observable<");
            
            #line 148 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(">(observer => {\r\n\t\t\t\tsetTimeout(() => {\r\n\t\t\t\t\tobserver.next(this.parse");
            
            #line 150 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(atob(cacheEntry), 200));\r\n\t\t\t\t}, 0);\r\n\t\t\t\tsetTimeout(() => {\r\n\t\t\t\t\tobserver.comp" +
                    "lete();\r\n\t\t\t\t}, 0);\r\n\t\t\t});\r\n\t\t}\r\n    }\r\n\r\n    protected process");
            
            #line 159 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(response: Response): ");
            
            #line 159 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.ResultType));
            
            #line default
            #line hidden
            this.Write(" {\r\n        const responseText = response.text();\r\n        const status = respons" +
                    "e.status; \r\n\r\n");
            
            #line 163 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var response in operation.Responses){
            
            #line default
            #line hidden
            this.Write("        if (status === ");
            
            #line 164 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(") {\r\n");
            
            #line 165 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(response.HasType){
            
            #line default
            #line hidden
            
            #line 166 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(response.IsDate){
            
            #line default
            #line hidden
            this.Write("            result");
            
            #line 167 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(" = new Date(data);\r\n");
            
            #line 168 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            
            #line 169 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      if(response.UseDtoClass){
            
            #line default
            #line hidden
            
            #line 170 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("            result");
            
            #line 171 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(" = data === \"\" ? null : <");
            
            #line 171 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.Type));
            
            #line default
            #line hidden
            this.Write(">JSON.parse(data, this.jsonParseReviver);\r\n");
            
            #line 172 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }
            
            #line default
            #line hidden
            
            #line 173 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 174 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(response.IsSuccess){
            
            #line default
            #line hidden
            this.Write("            return this.parse");
            
            #line 175 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(responseText, status);\r\n");
            
            #line 176 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("            throw result");
            
            #line 177 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write("; \r\n");
            
            #line 178 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
}
            
            #line default
            #line hidden
            this.Write("        }\r\n        else\r\n");
            
            #line 182 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 183 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasDefaultResponse){
            
            #line default
            #line hidden
            
            #line 184 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(operation.DefaultResponse.IsDate){
            
            #line default
            #line hidden
            this.Write("            result = new Date(data);\r\n");
            
            #line 186 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            
            #line 187 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      if(operation.DefaultResponse.UseDtoClass){
            
            #line default
            #line hidden
            
            #line 188 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("            result = data === \"\" ? null : <");
            
            #line 189 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.DefaultResponse.Type));
            
            #line default
            #line hidden
            this.Write(">JSON.parse(data, this.jsonParseReviver);\r\n");
            
            #line 190 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }
            
            #line default
            #line hidden
            
            #line 191 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 192 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(operation.DefaultResponse.IsSuccess){
            
            #line default
            #line hidden
            this.Write("            return this.parse");
            
            #line 193 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(data, status);\r\n");
            
            #line 194 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("            throw result; \r\n");
            
            #line 196 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
}else{
            
            #line default
            #line hidden
            this.Write("            throw new Error(\"error_no_callback_for_the_received_http_status\"); \r\n" +
                    "");
            
            #line 199 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n\r\n    private parse");
            
            #line 203 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.OperationNameUpper));
            
            #line default
            #line hidden
            this.Write("(data: string, status: number) {\r\n");
            
            #line 204 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
foreach(var response in operation.Responses){
            
            #line default
            #line hidden
            this.Write("        if (status === ");
            
            #line 205 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(") {\r\n");
            
            #line 206 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(response.HasType){
            
            #line default
            #line hidden
            this.Write("            let result");
            
            #line 207 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(": ");
            
            #line 207 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.Type));
            
            #line default
            #line hidden
            this.Write(" = null; \r\n");
            
            #line 208 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(response.IsDate){
            
            #line default
            #line hidden
            this.Write("            result");
            
            #line 209 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(" = new Date(data);\r\n");
            
            #line 210 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            
            #line 211 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      if(response.UseDtoClass){
            
            #line default
            #line hidden
            this.Write("            let resultData");
            
            #line 212 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(" = data === \"\" ? null : JSON.parse(data, this.jsonParseReviver);\r\n            ");
            
            #line 213 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConversionUtilities.Tab(response.DataConversionCode, 3)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 214 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("            result");
            
            #line 215 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write(" = data === \"\" ? null : <");
            
            #line 215 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.Type));
            
            #line default
            #line hidden
            this.Write(">JSON.parse(data, this.jsonParseReviver);\r\n");
            
            #line 216 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }
            
            #line default
            #line hidden
            
            #line 217 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 218 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(response.IsSuccess){
            
            #line default
            #line hidden
            this.Write("            return result");
            
            #line 219 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write("; \r\n");
            
            #line 220 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("            throw result");
            
            #line 221 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(response.StatusCode));
            
            #line default
            #line hidden
            this.Write("; \r\n");
            
            #line 222 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
}
            
            #line default
            #line hidden
            this.Write("        }\r\n        else\r\n");
            
            #line 226 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        {\r\n");
            
            #line 227 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
if(operation.HasDefaultResponse){
            
            #line default
            #line hidden
            this.Write("            let result: ");
            
            #line 228 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.DefaultResponse.Type));
            
            #line default
            #line hidden
            this.Write(" = null; \r\n");
            
            #line 229 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(operation.DefaultResponse.IsDate){
            
            #line default
            #line hidden
            this.Write("            result = new Date(data);\r\n");
            
            #line 231 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            
            #line 232 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      if(operation.DefaultResponse.UseDtoClass){
            
            #line default
            #line hidden
            this.Write("            let resultData = data === \"\" ? null : JSON.parse(data, this.jsonParse" +
                    "Reviver);\r\n            ");
            
            #line 234 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ConversionUtilities.Tab(operation.DefaultResponse.DataConversionCode, 3)));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 235 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }else{
            
            #line default
            #line hidden
            this.Write("            result = data === \"\" ? null : <");
            
            #line 236 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(operation.DefaultResponse.Type));
            
            #line default
            #line hidden
            this.Write(">JSON.parse(data, this.jsonParseReviver);\r\n");
            
            #line 237 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
      }
            
            #line default
            #line hidden
            
            #line 238 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
            
            #line default
            #line hidden
            
            #line 239 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  if(operation.DefaultResponse.IsSuccess){
            
            #line default
            #line hidden
            this.Write("            return result; \r\n");
            
            #line 241 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }else{
            
            #line default
            #line hidden
            this.Write("            throw result; \r\n");
            
            #line 243 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
  }
}else{
            
            #line default
            #line hidden
            this.Write("            throw new Error(\"error_no_callback_for_the_received_http_status\"); \r\n" +
                    "");
            
            #line 246 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("        }\r\n\t}\r\n");
            
            #line 249 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 251 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TemplatePartGenerator.RenderClientMethodsCode(Model, 1)));
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n");
            
            #line 253 "C:\HQSB\NSwag\src\NSwag.CodeGeneration\CodeGenerators\TypeScript\Templates\Angular2ClientTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal class Angular2ClientTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
